spring.datasource.url=jdbc:mysql://localhost:3306/hubinova
spring.datasource.username=root
spring.datasource.password=${<senhamysql>}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

api.security.token.secret=rFob3KuESne6SQsSQkR7pWEdLbpW1YbuRuS1S8kZqVV83+P3hEKa5Kyi2AGK1g/x8fruJ4QBwjhd0F6KOmj9aA==
server.port=8081
logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.web=DEBUG
logging.level.br.com.apihubinovacao=DEBUG