
#spring.datasource.url=jdbc:mysql://172.26.44.9:3306/hubinova
#jdbc:mysql://host.docker.internal:3306/hubinova
#spring.datasource.url=jdbc:mysql://localhost:3306/hubinova

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


api.security.token.secret=${JWT_SECRET}


server.port=${APP_PORT}


logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.br.com.apihubinovacao=DEBUG