version: '3.8'

services:
  app:
    build: .
    container_name: service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xmx512m
    restart: unless-stopped
    volumes:
      - /Users/miguelamaral/Documents/dev/api-hub-inovacao/api-hub-inovacao/uploads:/app/uploads